use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::core::{CoreError, Result};

/// 锁文件中记录的单个工具
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LockedTool {
    /// 传递给 install 的包名（如 python3.11, rg）
    pub recipe: String,
    /// 安装的精确版本（可能含 + 等字符，如 17.0.20+8）
    pub version: String,
    /// 归档 SHA256（hex）
    pub sha256: String,
    /// 配方来源: builtin | community | dynamic | registry | unknown
    pub source: String,
    /// 归档下载地址
    pub archive_url: String,
}

/// package-lock 风格的锁文件
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Lockfile {
    /// 锁文件格式版本
    pub version: u32,
    /// 工具族名 → 锁定条目（如 "python"）
    #[serde(default)]
    pub tools: BTreeMap<String, LockedTool>,
}

impl Lockfile {
    /// 序列化为 YAML（带生成注释头）
    pub fn to_yaml(&self) -> Result<String> {
        let mut s = String::from(
            "# Generated by oneinit freeze\n# Run oneinit sync on new machine to restore\n",
        );
        s.push_str(
            &serde_yaml::to_string(self)
                .map_err(|e| CoreError::Other(format!("YAML serialize failed: {}", e)))?,
        );
        Ok(s)
    }

    /// 从 YAML 内容解析（注释行由 serde_yaml 自动忽略）
    pub fn from_yaml(content: &str) -> Result<Lockfile> {
        serde_yaml::from_str(content)
            .map_err(|e| CoreError::Other(format!("YAML parse failed: {}", e)))
    }

    /// 写入锁文件
    pub fn write(path: &Path, lock: &Lockfile) -> Result<()> {
        let content = lock.to_yaml()?;
        std::fs::write(path, content)?;
        Ok(())
    }

    /// 读取锁文件（不存在则返回 None）
    pub fn read(path: &Path) -> Result<Option<Lockfile>> {
        if !path.exists() {
            return Ok(None);
        }
        let content = std::fs::read_to_string(path)?;
        Ok(Some(Self::from_yaml(&content)?))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_lock() -> Lockfile {
        let mut tools = BTreeMap::new();
        tools.insert(
            "python".to_string(),
            LockedTool {
                recipe: "python3.11".to_string(),
                version: "3.11.9".to_string(),
                sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
                    .to_string(),
                source: "builtin".to_string(),
                archive_url: "https://example.com/python-3.11.9.tar.gz".to_string(),
            },
        );
        tools.insert(
            "rg".to_string(),
            LockedTool {
                recipe: "rg".to_string(),
                version: "15.2.0".to_string(),
                sha256: "d6a1f5c3d8b0e9a27e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934c"
                    .to_string(),
                source: "dynamic".to_string(),
                archive_url: "https://example.com/rg-15.2.0.zip".to_string(),
            },
        );
        Lockfile { version: 1, tools }
    }

    #[test]
    fn test_lockfile_roundtrip() {
        let lock = sample_lock();
        let yaml = lock.to_yaml().unwrap();
        assert!(yaml.starts_with(
            "# Generated by oneinit freeze\n# Run oneinit sync on new machine to restore\n"
        ));
        let parsed = Lockfile::from_yaml(&yaml).unwrap();
        assert_eq!(parsed, lock);
    }

    #[test]
    fn test_lockfile_java_plus_version_roundtrip() {
        let mut tools = BTreeMap::new();
        tools.insert(
            "java".to_string(),
            LockedTool {
                recipe: "java17".to_string(),
                version: "17.0.20+8".to_string(),
                sha256: "a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90"
                    .to_string(),
                source: "builtin".to_string(),
                archive_url: "https://example.com/jdk-17.0.20+8.tar.gz".to_string(),
            },
        );
        let lock = Lockfile { version: 1, tools };
        let yaml = lock.to_yaml().unwrap();
        let parsed = Lockfile::from_yaml(&yaml).unwrap();
        assert_eq!(parsed, lock);
        // 版本号原样保留（含 +）
        assert_eq!(parsed.tools["java"].version, "17.0.20+8");
    }

    #[test]
    fn test_lockfile_empty_tools() {
        let lock = Lockfile {
            version: 1,
            tools: BTreeMap::new(),
        };
        let yaml = lock.to_yaml().unwrap();
        assert!(
            yaml.contains("tools: {}"),
            "expected tools: {{}} in yaml, got:\n{}",
            yaml
        );
        let parsed = Lockfile::from_yaml(&yaml).unwrap();
        assert!(parsed.tools.is_empty());
        assert_eq!(parsed, lock);
    }

    #[test]
    fn test_lockfile_write_read() {
        let dir = std::env::temp_dir();
        let path = dir.join("oneinit_test_lockfile.yaml");
        let _ = std::fs::remove_file(&path);

        let lock = sample_lock();
        Lockfile::write(&path, &lock).unwrap();
        let read = Lockfile::read(&path)
            .unwrap()
            .expect("lockfile should exist");
        assert_eq!(read, lock);

        // 不存在的路径 → None
        let missing = dir.join("oneinit_test_lockfile_missing.yaml");
        assert!(Lockfile::read(&missing).unwrap().is_none());

        let _ = std::fs::remove_file(&path);
    }
}
