//! 配方向导：没有现成配方时的处理流程。
//!
//! 当 `oneinit install <tool>` 找不到配方时，给用户两种选择：
//!
//!   1. 查看手动安装教程（自己按步骤安装）
//!   2. 生成一个配方并用 oneinit 安装
//!
//! 安装配置好环境后，询问用户是否贡献配方 —— 两种方式：
//!
//!   1. git 推送到配方仓库（oneinitAI/oneinit-recipes）
//!   2. 上传到 oneinit.bg4jts.cn（后端尚未上线，接口已预留）

use std::io::Write;
use std::path::PathBuf;

use super::community_recipe::{CommunityRecipe, Maintainer, PlatformConfig, Platforms};
use super::{CoreError, Result, recipes_dir};
use crate::output::OutputFormatter;

/// 向导动作
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WizardChoice {
    /// 显示手动安装教程
    Tutorial,
    /// 生成配方并用 oneinit 安装
    Generate,
}

/// 上传接口地址（oneinit.bg4jts.cn 配方服务，后端尚未上线）
const UPLOAD_ENDPOINT: &str = "https://oneinit.bg4jts.cn/api/v1/recipes";

/// 交互式读取一行输入；EOF/失败返回 None。
fn read_line(prompt: &str) -> Option<String> {
    print!("{prompt}");
    std::io::stdout().flush().ok()?;
    let mut input = String::new();
    if std::io::stdin().read_line(&mut input).is_err() {
        return None;
    }
    Some(input.trim().to_string())
}

/// 交互式 y/N 确认；EOF 视为否。
fn confirm(prompt: &str) -> bool {
    match read_line(prompt) {
        Some(a) => a.eq_ignore_ascii_case("y"),
        None => false,
    }
}

/// 没有现成配方时，询问用户如何继续。
/// 返回 None 表示取消（或非交互环境）。
pub fn prompt_action(tool: &str) -> Option<WizardChoice> {
    println!(
        "\n[WIZARD] 没有找到 '{}' 的现成配方。请选择如何继续：",
        tool
    );
    println!("  1) 📖 查看手动安装教程（自己按步骤安装）");
    println!("  2) 🧩 生成一个配方并用 oneinit 安装");
    println!("  3) ❌ 取消");
    match read_line("输入 1/2/3: ")?.as_str() {
        "1" => Some(WizardChoice::Tutorial),
        "2" => Some(WizardChoice::Generate),
        _ => None,
    }
}

/// 生成手动安装教程文本。
pub fn tutorial(tool: &str) -> String {
    format!(
        "\n[WIZARD] 手动安装教程：{}\n\
         ─────────────────────────────────────────\n\
         \x20 1. 打开官方下载页：搜索 \"{} 官方下载\" 或访问官网（常见：https://{}.org 或 https://github.com/{}/{})\n\
         \x20 2. 下载适合你系统的安装包（Windows x64 / Linux x64 / macOS）\n\
         \x20 3. 运行安装程序，或解压到 ~/tools/{}\n\
         \x20 4. 把可执行文件所在目录加入 PATH（Windows: 系统设置→环境变量）\n\
         \x20 5. 验证安装：{} --version\n\
         ─────────────────────────────────────────\n\
         \x20 安装完成后：\n\
         \x20   • 运行 `oneinit capture` 让 oneinit 记录你的环境\n\
         \x20   • 或运行 `oneinit recipe wizard {}` 生成配方，方便下次一键安装\n",
        tool, tool, tool, tool, tool, tool, tool, tool
    )
}

/// 根据 URL 后缀推断安装类型。
fn infer_install_type(url: &str) -> &'static str {
    let lower = url.to_lowercase();
    if lower.ends_with(".zip") {
        "zip_extract"
    } else if lower.ends_with(".tar.gz") || lower.ends_with(".tgz") || lower.ends_with(".tar.xz") {
        "tar_extract"
    } else if lower.ends_with(".exe") || lower.ends_with(".msi") {
        "exe_silent"
    } else {
        "zip_extract"
    }
}

/// 交互式生成一个配方（当前平台）。
/// 用户取消关键输入（下载地址）时返回 Err。
pub fn interactive_build_recipe(tool: &str) -> Result<CommunityRecipe> {
    let url = read_line(
        "\n[WIZARD] 生成配方 —— 请提供以下信息（可选项目直接回车跳过）：\n  下载地址 URL (必需): ",
    )
    .ok_or_else(|| CoreError::Other("已取消配方向导".into()))?;
    if url.trim().is_empty() {
        return Err(CoreError::Other("下载地址不能为空，已取消".into()));
    }
    let url = url.trim().to_string();

    let sha = read_line("  sha256 校验和 (可选，回车跳过): ").unwrap_or_default();
    let sha = sha.trim().to_string();

    let default_type = infer_install_type(&url);
    let it = read_line(&format!(
        "  安装类型 [{}] (zip_extract/tar_extract/exe_silent/binary_copy): ",
        default_type
    ))
    .unwrap_or_default();
    let install_type = if it.trim().is_empty() {
        default_type.to_string()
    } else {
        it.trim().to_string()
    };

    let path_dir =
        read_line("  加入 PATH 的目录 (可选，如 bin，回车用安装目录本身): ").unwrap_or_default();
    let path_dir = path_dir.trim().to_string();

    let desc = read_line("  描述 (可选): ").unwrap_or_default();
    let description = if desc.trim().is_empty() {
        format!("{} (generated by oneinit recipe wizard)", tool)
    } else {
        desc.trim().to_string()
    };

    let version = read_line("  版本号 (可选，默认 1.0.0): ").unwrap_or_default();
    let version = if version.trim().is_empty() {
        "1.0.0".to_string()
    } else {
        version.trim().to_string()
    };

    let path_add = if path_dir.is_empty() {
        vec!["{{install_dir}}".to_string()]
    } else {
        vec![format!("{{{{install_dir}}}}/{}", path_dir)]
    };

    let platform_cfg = PlatformConfig {
        url,
        sha256: sha,
        install_type,
        install_args: None,
        install_path: format!("{}-wizard", tool),
        path_add,
    };

    Ok(CommunityRecipe {
        name: tool.to_string(),
        version,
        description,
        license: None,
        license_url: None,
        platforms: Platforms {
            windows: if cfg!(target_os = "windows") {
                Some(platform_cfg.clone())
            } else {
                None
            },
            linux: if cfg!(target_os = "linux") {
                Some(platform_cfg.clone())
            } else {
                None
            },
            darwin: if cfg!(target_os = "macos") {
                Some(platform_cfg)
            } else {
                None
            },
        },
        post_install: None,
        depends: None,
        tags: Some(vec!["wizard".to_string(), "generated".to_string()]),
        maintainer: Some(current_git_identity()),
    })
}

/// 从 git 配置尝试读取用户身份（用于配方 maintainer 字段）。
fn current_git_identity() -> Maintainer {
    let name = git_config("user.name");
    let email = git_config("user.email");
    let github = email
        .as_deref()
        .and_then(|e| e.strip_suffix("@users.noreply.github.com"))
        .or_else(|| email.as_deref().map(|e| e.split('@').next().unwrap_or("")))
        .filter(|s| !s.is_empty())
        .map(|s| s.to_string());
    Maintainer {
        name: name.filter(|s| !s.is_empty()),
        github,
        email,
    }
}

fn git_config(key: &str) -> Option<String> {
    let out = std::process::Command::new("git")
        .args(["config", "--get", key])
        .output()
        .ok()?;
    if out.status.success() {
        Some(String::from_utf8_lossy(&out.stdout).trim().to_string())
    } else {
        None
    }
}

/// 保存配方到 ~/.oneinit/recipes/<name>.yaml，返回文件路径。
pub fn save_recipe(recipe: &CommunityRecipe) -> Result<PathBuf> {
    let dir = recipes_dir();
    std::fs::create_dir_all(&dir)?;
    let path = dir.join(format!("{}.yaml", recipe.name));
    let yaml = serde_yaml::to_string(recipe)
        .map_err(|e| CoreError::Other(format!("YAML serialize failed: {}", e)))?;
    std::fs::write(&path, yaml)?;
    Ok(path)
}

/// 从任意路径加载配方 YAML。
pub fn load_recipe_file(path: &std::path::Path) -> Result<CommunityRecipe> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| CoreError::Other(format!("读取配方文件失败: {}", e)))?;
    serde_yaml::from_str(&content)
        .map_err(|e| CoreError::Other(format!("解析配方 YAML 失败: {}", e)))
}

/// 安装配置好环境后，询问用户是否贡献配方，并给出两种贡献方式。
pub async fn offer_contribution(
    recipe: &CommunityRecipe,
    formatter: &OutputFormatter,
) -> Result<()> {
    println!();
    if !confirm("[WIZARD] 环境配置完成！是否愿意把这个配方贡献给社区？(y/N): ")
    {
        formatter.output(
            &format!(
                "[WIZARD] 好的，配方已保留在本地：~/.oneinit/recipes/{}.yaml，随时可以贡献。",
                recipe.name
            ),
            Some(serde_json::json!({
                "action": "recipe_contribute",
                "status": "skipped",
                "recipe": recipe.name,
            })),
        );
        return Ok(());
    }

    // 确保配方已保存
    let path = save_recipe(recipe)?;

    println!("\n[WIZARD] 感谢贡献！请选择贡献方式：");
    println!("  1) 📦 上传到 oneinit.bg4jts.cn（自动上传，推荐）");
    println!("  2) 🌿 通过 git 提交到配方仓库（oneinitAI/oneinit-recipes）");
    match read_line("输入 1/2: ").as_deref() {
        Some("1") => match upload_recipe(recipe).await {
            Ok(()) => Ok(()),
            Err(e) => {
                formatter.output(
                    &format!("[WIZARD] {}（配方已保留：{}）", e, path.display()),
                    Some(serde_json::json!({
                        "action": "recipe_contribute",
                        "status": "upload_pending",
                        "recipe": recipe.name,
                        "file": path.to_string_lossy(),
                    })),
                );
                Ok(())
            }
        },
        Some("2") => {
            formatter.output(
                &git_contribution_instructions(recipe),
                Some(serde_json::json!({
                    "action": "recipe_contribute",
                    "status": "git_instructions",
                    "recipe": recipe.name,
                    "file": path.to_string_lossy(),
                    "repo": "https://github.com/oneinitAI/oneinit-recipes",
                })),
            );
            Ok(())
        }
        _ => {
            formatter.output(
                &format!("[WIZARD] 已取消贡献。配方保留在：{}", path.display()),
                Some(serde_json::json!({
                    "action": "recipe_contribute",
                    "status": "cancelled",
                    "recipe": recipe.name,
                })),
            );
            Ok(())
        }
    }
}

/// git 贡献方式的说明。
pub fn git_contribution_instructions(recipe: &CommunityRecipe) -> String {
    format!(
        "\n[WIZARD] 通过 git 提交配方（需要 GitHub 账号）：\n\
         ─────────────────────────────────────────\n\
         \x20 1. Fork 配方仓库：https://github.com/oneinitAI/oneinit-recipes\n\
         \x20 2. 克隆并创建分支：\n\
         \x20    git clone https://github.com/<你的账号>/oneinit-recipes.git\n\
         \x20    cd oneinit-recipes && git checkout -b add-{}-recipe\n\
         \x20 3. 复制配方文件：\n\
         \x20    cp ~/.oneinit/recipes/{}.yaml recipes/\n\
         \x20 4. 提交并推送：\n\
         \x20    git add recipes/{}.yaml\n\
         \x20    git commit -m \"add {} recipe\"\n\
         \x20    git push origin add-{}-recipe\n\
         \x20 5. 在 GitHub 创建 Pull Request（base: oneinitAI/oneinit-recipes）\n\
         ─────────────────────────────────────────\n",
        recipe.name, recipe.name, recipe.name, recipe.name, recipe.name
    )
}

/// 上传配方到 oneinit.bg4jts.cn（接口已预留，后端尚未上线）。
///
/// 接口约定：
///   POST {UPLOAD_ENDPOINT}
///   Content-Type: application/yaml
///   body: 配方 YAML
pub async fn upload_recipe(recipe: &CommunityRecipe) -> Result<()> {
    let yaml = serde_yaml::to_string(recipe)
        .map_err(|e| CoreError::Other(format!("YAML serialize failed: {}", e)))?;
    let client = super::self_update::http_client()?;
    let resp = client
        .post(UPLOAD_ENDPOINT)
        .header("Content-Type", "application/yaml")
        .body(yaml)
        .send()
        .await;
    match resp {
        Ok(r) if r.status().is_success() => Ok(()),
        _ => Err(CoreError::Other(format!(
            "上传服务（{}）尚未就绪，暂时无法在线提交",
            UPLOAD_ENDPOINT
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tutorial_contains_tool() {
        let t = tutorial("k9s");
        assert!(t.contains("k9s"));
        assert!(t.contains("--version"));
    }

    #[test]
    fn test_infer_install_type() {
        assert_eq!(infer_install_type("https://x.com/a.zip"), "zip_extract");
        assert_eq!(infer_install_type("https://x.com/a.tar.gz"), "tar_extract");
        assert_eq!(infer_install_type("https://x.com/a.exe"), "exe_silent");
    }

    #[test]
    fn test_recipe_yaml_roundtrip() {
        let recipe = CommunityRecipe {
            name: "mycli".to_string(),
            version: "1.0.0".to_string(),
            description: "test".to_string(),
            license: None,
            license_url: None,
            platforms: Platforms {
                windows: Some(PlatformConfig {
                    url: "https://example.com/mycli.zip".to_string(),
                    sha256: String::new(),
                    install_type: "zip_extract".to_string(),
                    install_args: None,
                    install_path: "mycli-wizard".to_string(),
                    path_add: vec!["{{install_dir}}/bin".to_string()],
                }),
                linux: None,
                darwin: None,
            },
            post_install: None,
            depends: None,
            tags: Some(vec!["wizard".to_string()]),
            maintainer: None,
        };
        let yaml = serde_yaml::to_string(&recipe).unwrap();
        let back: CommunityRecipe = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(back.name, "mycli");
        assert_eq!(back.platforms.windows.unwrap().install_type, "zip_extract");
    }
}
